src/Assignment2/Models/Enquiry.cs
using System.ComponentModel.DataAnnotations;

namespace Assignment2.Models
{
    public class Enquiry
    {
        public int EnquiryID { get; set; }

        [Required(ErrorMessage = "Please enter your Email Address")]
        [MaxLength(50)]
        [RegularExpression(@"[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}", ErrorMessage = "Please enter correct email")]
        public string Email { get; set; }

        [Required]
        public string Message { get; set; }
    }
}

src/Assignment2/Controllers/EnquiryController.cs
using Assignment2.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Data.SqlClient;

public class EnquiryController : Controller
{
    // GET: Home
    public ActionResult Index()
    {
        return View();
    }


    [HttpPost]
    public ActionResult Index(Enquiry enq)
    {
        string connectionString = null;
        string sql = null;


        connectionString = @"Data Source=.\SQLEXPRESS; Initial Catalog=Assignment2; Trusted_Connection=True";

        using (SqlConnection cnn = new SqlConnection(connectionString))
        {
            sql = "insert into Enquiry (Email, [Message]) values (@Email, @Message)";
            cnn.Open();

            using (SqlCommand cmd = new SqlCommand(sql, cnn))
            {
                cmd.Parameters.AddWithValue("@Email", enq.Email);
                cmd.Parameters.AddWithValue("@Message", enq.Message);

                if (ModelState.IsValid)
                {
                    cmd.ExecuteNonQuery();
                    cnn.Close();
                    ViewBag.Message = "1";
                    return RedirectToAction("Index");
                }
                return View(enq);
            }
        }
    }
}

src/Assignment2/Views/Enquiry/Index.cshtml
@model Assignment2.Models.Enquiry

@{
    ViewData["Title"] = "Index";
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <style type="text/css">
        body {
            font-family: Arial;
            font-size: 10pt;
        }

        table {
            border: 1px solid #ccc;
            border-collapse: collapse;
            background-color: #fff;
            align-content: center;
        }

            table.center {
                margin-left: auto;
                margin-right: auto;
            }

        .information {
            bottom: 50px;
            text-align: center;
            border: solid;
            font-family: Cambria;
            font-size: 20px;
        }

        table th {
            background-color: #B8DBFD;
            color: #333;
            font-weight: bold;
        }

        table th, table td {
            padding: 5px;
            border: 1px solid #ccc;
        }

        table, table table td {
            border: 0px solid #ccc;
        }

        input[type=text], select {
            width: 150px;
        }
    </style>
</head>
<body>
    <p class="information">
        ABCCC hosts special corporate events to raise money.<br /> You can submit your enquiries about these special events.<br />
        Please use the form below to submit your enquiries to the admin personnel's email.
    </p>

    @using (Html.BeginForm("Index", "Enquiry", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <table class="center" cellpadding="0" cellspacing="0">
            <tr>
                <th colspan="2" align="center">Enquiry Form</th>
            </tr>
            <tr>
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <td>@Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" }) </td>
                <td>
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </td>
            </tr>
            <tr>
                <th colspan="2" align="center"></th>
            </tr>
            <tr>
                <td>@Html.LabelFor(model => model.Message, htmlAttributes: new { @class = "control-label col-md-2" }) </td>
                <td>
                    @Html.TextAreaFor(enq => enq.Message, new { @rows = 10, @cols = 60 })<br />
                    @Html.ValidationMessageFor(model => model.Message, "", new { @class = "text-danger" })
                </td>
            </tr>
            <tr>
                <td></td>
                <td><input type="submit" value="Submit" /></td>
            </tr>
        </table>
    }

    @*<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    @if (Model != null)
    {
        <script type="text/javascript">
            $(function () {
                alert("Enquiry has been submitted to Events Admin. Thanks for your support!");
            });
        </script>
    }*@
    @Scripts.Render("~/bundles/jquery")

    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js">
    $(document).ready(function () {

        var msg = '@ViewData["Message"]';
        if(msg=='1')
        alert("you are done with your thing");
    });
    </script>


    @RenderSection("Scripts", required: false)
    
</body>
</html>