src/Assignment2/Controllers/CineplexMoviesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Assignment2.Models;
using System.Globalization;

namespace Assignment2.Controllers
{
    public class CineplexMoviesController : Controller
    {
        private readonly Assignment2Context _context;

        public CineplexMoviesController(Assignment2Context context)
        {
            _context = context;    
        }

        // GET: CineplexMovies
        public async Task<IActionResult> Index(string sortOrder, string searchString)
        {
            /*var assignment2Context = _context.CineplexMovie.Include(c => c.Cineplex).Include(c => c.Movie).Include(c => c.Session);
            return View(await assignment2Context.ToListAsync());*/
            ViewData["MovieSortParm"] = String.IsNullOrEmpty(sortOrder) ? "movie_desc" : "";
            ViewData["CinemaSortParm"] = sortOrder == "cin" ? "cinema_loc" : "cin";
            ViewData["CurrentFilter"] = searchString;
            
            var cinemovie = from m in _context.CineplexMovie.Include(c => c.Cineplex).Include(c => c.Movie).Include(c => c.Session)
                            select m;
            /*var currentCulture = CultureInfo.CurrentCulture;
            foreach (var m in cinemovie)
            {
                var date = m.Session.SessionTime1;
                var mdate = currentCulture.Calendar.GetWeekOfYear(
                            DateTime.Now,
                            currentCulture.DateTimeFormat.CalendarWeekRule,
                            currentCulture.DateTimeFormat.FirstDayOfWeek);
                var now = currentCulture.Calendar.GetWeekOfYear(
                            DateTime.Now,
                            currentCulture.DateTimeFormat.CalendarWeekRule,
                            currentCulture.DateTimeFormat.FirstDayOfWeek);

                cinemovie = cinemovie.Where(mdate==now);
            }


            IQueryable <CineplexMovie> movies;
            
            var weekNo = currentCulture.Calendar.GetWeekOfYear(
                            DateTime.Now,
                            currentCulture.DateTimeFormat.CalendarWeekRule,
                            currentCulture.DateTimeFormat.FirstDayOfWeek);

            foreach (var y in cinemovie)
            {
                var weekNo2 = currentCulture.Calendar.GetWeekOfYear(
                                y.Session.SessionTime1,
                                currentCulture.DateTimeFormat.CalendarWeekRule,
                                currentCulture.DateTimeFormat.FirstDayOfWeek);
                var weekNo3 = currentCulture.Calendar.GetWeekOfYear(
                                y.Session.SessionTime2,
                                currentCulture.DateTimeFormat.CalendarWeekRule,
                                currentCulture.DateTimeFormat.FirstDayOfWeek);
                if (weekNo == weekNo2 && weekNo == weekNo3)
                {
                    cinemovie = cinemovie.Where(weekNo2);
                }

            }*/


            if (!String.IsNullOrEmpty(searchString))
            {
                cinemovie = cinemovie.Where(s => s.Movie.Title.Contains(searchString)
                                            || s.Cineplex.Location.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "cinema_loc":
                    cinemovie = cinemovie.OrderByDescending(s => s.Cineplex.Location);
                    break;
                case "cin":
                    cinemovie = cinemovie.OrderBy(s => s.Cineplex.Location);
                    break;
                case "movie_desc":
                    cinemovie = cinemovie.OrderByDescending(s => s.Movie.Title);
                    break;
                default:
                    cinemovie = cinemovie.OrderBy(s => s.Movie.Title);
                    break;
            }
            return View(await cinemovie.AsNoTracking().ToListAsync());
        }

        // GET: CineplexMovies/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            
            var cineplexMovie = await _context.CineplexMovie
                .Include(c => c.Cineplex)
                .Include(c => c.Movie)
                .Include(c => c.Session)
                .AsNoTracking()
                   .SingleOrDefaultAsync(m => m.CineplexId == id);
            /*var cineplexMovie = await _context.CineplexMovie.SingleOrDefaultAsync(m => m.CineplexId == id);*/
            if (cineplexMovie == null)
            {
                return NotFound();
            }

            return View(cineplexMovie);
        }

        // GET: CineplexMovies/Create
        public IActionResult Create()
        {
            ViewData["CineplexId"] = new SelectList(_context.Cineplex, "CineplexId", "Location");
            ViewData["MovieId"] = new SelectList(_context.Movie, "MovieId", "LongDescription");
            ViewData["SessionId"] = new SelectList(_context.SessionTime, "SessionTimeId", "SessionTimeId");
            return View();
        }

        // POST: CineplexMovies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CineplexId,MovieId,SessionId")] CineplexMovie cineplexMovie)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cineplexMovie);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewData["CineplexId"] = new SelectList(_context.Cineplex, "CineplexId", "Location", cineplexMovie.CineplexId);
            ViewData["MovieId"] = new SelectList(_context.Movie, "MovieId", "LongDescription", cineplexMovie.MovieId);
            ViewData["SessionId"] = new SelectList(_context.SessionTime, "SessionTimeId", "SessionTimeId", cineplexMovie.SessionId);
            return View(cineplexMovie);
        }

        // GET: CineplexMovies/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cineplexMovie = await _context.CineplexMovie.SingleOrDefaultAsync(m => m.CineplexId == id);
            if (cineplexMovie == null)
            {
                return NotFound();
            }
            ViewData["CineplexId"] = new SelectList(_context.Cineplex, "CineplexId", "Location", cineplexMovie.CineplexId);
            ViewData["MovieId"] = new SelectList(_context.Movie, "MovieId", "LongDescription", cineplexMovie.MovieId);
            ViewData["SessionId"] = new SelectList(_context.SessionTime, "SessionTimeId", "SessionTimeId", cineplexMovie.SessionId);
            return View(cineplexMovie);
        }

        // POST: CineplexMovies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CineplexId,MovieId,SessionId")] CineplexMovie cineplexMovie)
        {
            if (id != cineplexMovie.CineplexId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cineplexMovie);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CineplexMovieExists(cineplexMovie.CineplexId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            ViewData["CineplexId"] = new SelectList(_context.Cineplex, "CineplexId", "Location", cineplexMovie.CineplexId);
            ViewData["MovieId"] = new SelectList(_context.Movie, "MovieId", "LongDescription", cineplexMovie.MovieId);
            ViewData["SessionId"] = new SelectList(_context.SessionTime, "SessionTimeId", "SessionTimeId", cineplexMovie.SessionId);
            return View(cineplexMovie);
        }

        // GET: CineplexMovies/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cineplexMovie = await _context.CineplexMovie.SingleOrDefaultAsync(m => m.CineplexId == id);
            if (cineplexMovie == null)
            {
                return NotFound();
            }

            return View(cineplexMovie);
        }

        // POST: CineplexMovies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cineplexMovie = await _context.CineplexMovie.SingleOrDefaultAsync(m => m.CineplexId == id);
            _context.CineplexMovie.Remove(cineplexMovie);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool CineplexMovieExists(int id)
        {
            return _context.CineplexMovie.Any(e => e.CineplexId == id);
        }
    }
}

src/Assignment2/Views/CineplexMovies/Create.cshtml
@model Assignment2.Models.CineplexMovie

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<form asp-action="Create">
    <div class="form-horizontal">
        <h4>CineplexMovie</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="SessionId" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <select asp-for="SessionId" class ="form-control" asp-items="ViewBag.SessionId"></select>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/Assignment2/Views/CineplexMovies/Delete.cshtml
@model Assignment2.Models.CineplexMovie

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CineplexMovie</h4>
    <hr />
    <dl class="dl-horizontal">
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

src/Assignment2/Views/CineplexMovies/Details.cshtml
@model Assignment2.Models.CineplexMovie
@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

@*<div>
        <h4>CineplexMovie</h4>
        <hr />
        <dl class="dl-horizontal">
        </dl>
    </div>
    <div>
        @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
        <a asp-action="Index">Back to List</a>
    </div>*@
<div>
    <h4>Student</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Movie Title: 
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Movie.Title)
        </dd>
        <dt>
            Cinema Location: 
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Cineplex.Location)
        </dd>
        <dt>
            Movie Description: 
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Movie.LongDescription)
        </dd>
        <dt>
            Session Times
        </dt>
        <dd>
            <table class="table">
                <tr>
                    <th>Session Time</th>
                </tr>
                <tr>
                    <td>
                        @Html.DisplayFor(model => model.Session.SessionTime1)
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.DisplayFor(model => model.Session.SessionTime1)
                    </td>
                </tr>
            </table>
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ })
    <a asp-action="Index">Back to List</a>
</div>

src/Assignment2/Views/CineplexMovies/Edit.cshtml
@model Assignment2.Models.CineplexMovie

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>CineplexMovie</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="CineplexId" />
    <input type="hidden" asp-for="MovieId" />
        <div class="form-group">
            <label asp-for="SessionId" class="control-label col-md-2"></label>
            <div class="col-md-10">
                <select asp-for="SessionId" class="form-control" asp-items="ViewBag.SessionId"></select>
                <span asp-validation-for="SessionId" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/Assignment2/Views/CineplexMovies/Index.cshtml
@model IEnumerable<Assignment2.Models.CineplexMovie>

@{
    ViewData["Title"] = "Sessions";
}

<h2>Movie Session</h2>

<form asp-controller="CineplexMovies" asp-action="Index">
        <p>
            Title: <input type="text" name="SearchString" value="@ViewData["currentFilter"]">
            <input type="submit" value="Filter" />
        </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th><a asp-action="Index" asp-route-sortOrder="@ViewBag.CinemaSortParm">@Html.DisplayNameFor(model => model.Cineplex.Location)</a></th>
            <th><a asp-action="Index" asp-route-sortOrder="@ViewBag.MovieSortParm">@Html.DisplayNameFor(model => model.Movie.Title)</a></th>
            <th>Short Desc</th>
            <th>Session Times</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var m in Model)
        {
            <tr>
                <td>@Html.DisplayFor(model => m.Cineplex.Location)</td>
                <td>@Html.DisplayFor(model => m.Movie.Title)</td>
                <td>@Html.DisplayFor(model => m.Movie.ShortDescription)</td>
                <td>@Html.DisplayFor(model => m.Session.SessionTime1, "ShortDateTime")</td>
                <td>@Html.DisplayFor(model => m.Session.SessionTime2, "ShortDateTime")</td>
            </tr>
        }
    </tbody>
</table>
@*<p>
        <a asp-action="Create">Create New</a>
    </p>
    <table class="table">
        <thead>
            <tr>
                <th></th>
            </tr>
        </thead>
        <tbody>
    @foreach (var item in Model) {
            <tr>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
                </td>
            </tr>
    }
        </tbody>
    </table>
*@